[workspace]
members = [
    "psy-k-bin",
    "psy-k-test-support",
]
resolver = "2"

[workspace.package]
version = "0.5.1"
authors = ["Jonathan Hohle <jon@ttkb.co>"]
license = "BSD-3-Clause"
repository = "https://github.com/ttkb-oss/psy-k"
keywords = ["psy-q", "dumpobj", "psylib", "obj", "psx"]
rust-version = "1.91.0"
edition = "2021"

[workspace.lints.rust]
unsafe_code = "forbid"

[package]
name = "psy-k"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "A PSY-Q object & library parser & utility."
keywords.workspace = true
categories = ["data-structures", "development-tools", "game-development", "parser-implementations"]
exclude = [
    ".gitignore",
    "/.github",
    "target/.private",
    "tests/data/psy-q",
]
readme = "README.md"
rust-version.workspace = true

[lib]
name = "psyk"

[dependencies]
binrw = { version = "0.15.0"}
chrono = "0.4"
rabbitizer = "1.14.3"
thiserror = "2.0.17"
unicode-segmentation = "1.12.0"
winnow = "0.7.14"

[dev-dependencies]
serde_json = "1.0.145"
psy-k-test-support = { version = "0", path = "psy-k-test-support" }

[build-dependencies]
# on macOS, cargo-spellcheck requires:
#    export DYLD_FALLBACK_LIBRARY_PATH= \
#        "$(xcode-select --print-path)/Toolchains/XcodeDefault.xctoolchain/usr/lib/"
#cargo-spellcheck = "0.15.5"

[lints]
workspace = true

[package.metadata.spellcheck]
config = ".config/spellcheck.toml"
