@ECHO OFF
IF NOT EXIST %1 GOTO NOTFOUND
ECHO Processing LIB: %1
TESTS\DATA\PSY-Q\3.6\PSYQ\BIN\PSYLIB.EXE /l %1 > %2
IF ERRORLEVEL 1 ECHO   ERROR processing %1
GOTO END
:NOTFOUND
ECHO   WARNING: File not found: %1
:END
